
package com.nevermind.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomServiceImplService", targetNamespace = "http://service.nevermind.com/", wsdlLocation = "http://localhost:10000/nevermind?wsdl")
public class CustomServiceImplService
    extends Service
{

    private final static URL CUSTOMSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CUSTOMSERVICEIMPLSERVICE_QNAME = new QName("http://service.nevermind.com/", "CustomServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10000/nevermind?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CUSTOMSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CustomServiceImplService() {
        super(__getWsdlLocation(), CUSTOMSERVICEIMPLSERVICE_QNAME);
    }

    public CustomServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMSERVICEIMPLSERVICE_QNAME, features);
    }

    public CustomServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMSERVICEIMPLSERVICE_QNAME);
    }

    public CustomServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMSERVICEIMPLSERVICE_QNAME, features);
    }

    public CustomServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NevermindName
     */
    @WebEndpoint(name = "CustomServiceImplPort")
    public NevermindName getCustomServiceImplPort() {
        return super.getPort(new QName("http://service.nevermind.com/", "CustomServiceImplPort"), NevermindName.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NevermindName
     */
    @WebEndpoint(name = "CustomServiceImplPort")
    public NevermindName getCustomServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.nevermind.com/", "CustomServiceImplPort"), NevermindName.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CUSTOMSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CUSTOMSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
