
package com.nevermind.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NevermindName", targetNamespace = "http://service.nevermind.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NevermindName {


    /**
     * 
     * @param usernameParam
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "greetingResult", targetNamespace = "")
    @RequestWrapper(localName = "welcomeOperation", targetNamespace = "http://service.nevermind.com/", className = "com.nevermind.service.WelcomeOperation")
    @ResponseWrapper(localName = "welcomeOperationResponse", targetNamespace = "http://service.nevermind.com/", className = "com.nevermind.service.WelcomeOperationResponse")
    @Action(input = "http://service.nevermind.com/NevermindName/welcomeOperationRequest", output = "http://service.nevermind.com/NevermindName/welcomeOperationResponse")
    public String welcomeOperation(
        @WebParam(name = "usernameParam", targetNamespace = "")
        String usernameParam);

}
